name: Request PR reviewers

on:
  # To support Dependabot PRs, we need to use `pull_request_target` instead of `pull_request`.
  #
  # See:
  # - https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-795140576
  # - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  request-front-end-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          # the default GITHUB_TOKEN does not have permission to request reviews from teams.
          # https://github.com/peter-evans/create-pull-request/issues/155#issuecomment-611904487
          github-token: ${{ secrets.REVIEW_REQUEST_GITHUB_TOKEN }}
          script: |
            return github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              team_reviewers: ['ruby']
            })
